import snapshot from "@/public/demo/tri-proof-sample-report.json"
import type { PublicDemoSnapshot } from "@/lib/demo/public-types"

// Generated by demo:generate; demo:check verifies the entire artifact against
// the typed engine output. Public routes read this snapshot, never live RPC.
export const publicDemoSnapshot = snapshot as PublicDemoSnapshot
