export {
  ENTITY_REGISTRY,
  ENTITY_REGISTRY_DATASET_VERSION,
  ENTITY_REGISTRY_SCHEMA_VERSION,
  KNOWN_ENTITIES,
  detectKnownEntity,
  entityRegistrySummary,
  isReviewOnlyEntityType,
  lookupEntityRegistry,
  normalizeEntityAddress,
  validateEntityRegistry,
  type EntityRegistryNetwork,
  type EntityRegistryRecord,
  type EntityRegistryRole,
  type EntityRegistrySourceKind,
  type EntityRegistryStatus,
  type KnownEntity,
} from "@/lib/entity-registry"
